"""empty message

Revision ID: 699014fa9316
Revises: 
Create Date: 2025-04-02 02:47:04.641576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '699014fa9316'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_booking', schema=None) as batch_op:
        batch_op.drop_column('total_fare')
        batch_op.drop_column('room_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_type', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('total_fare', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
